name: Docker Image CI

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Check Dockerfile
      uses: docker/build-psuh-action@v2
      with:
        context: ./
        file: container/Dockerfile
    
    - name: Build Docker image
      shell: bash
      run: docker build . --file container/Dockerfile --tag genomicmedicinesweden/jasen:latest
    
    - name: Push Docker image to Dockerhub
      shell: bash
      run: docker push genomicmedicinesweden/jasen:latest
