name: Docker Image CI

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
       id: buildx
       uses: docker/setup-buildx-action@v1

     - name: Check out pipeline code 
       uses: docker/build-push-action@v2
       with:
         context: ./
         file: container/Dockerfile
    
    - name: Build Docker image
      shell: bash
      run: docker build . --file container/Dockerfile --tag jd21/jasen:latest
    
    - name: Push Docker image to Dockerhub
      shell: bash
      run: docker push jd21/jasen:latest
